# note: we don't use separate python / c environments because the different
# codebases are interdependent

language: rust
rust:
  - stable
addons:
    apt:
        packages:
            - libssl-dev
            - python-pip
cache:
  - cargo
  - directories:
    - target
    - ~/.cache/pip
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update -q
install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install python3.6 openjdk-8-jdk swig
  - python -m pip install -r bindings/python/requirements.txt --user

script:
  - ls /usr/lib/jvm
  - make test
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --coveralls tXbFAsGMIvTHknGnhtBBNfqFjLitR9nTr --skip-clean --verbose -e battlecode-frankenstein
    fi
  
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=tXbFAsGMIvTHknGnhtBBNfqFjLitR9nTr
