[package]
name = "battlecode-engine-c"
version = "0.1.0"
authors = ["James Gilles <jhgilles@mit.edu>"]

[lib]
name = "libbattlecode"
crate-type = ["cdylib"]

[dependencies]
battlecode-engine = {path = "../battlecode-engine"}

[build-dependencies]
# generate c header files
moz-cheddar = "0.4.0"
